export const PER_PAGE = 5;
export const NONPROFIT_ELIGIBILITY = "12";

export const FOCUS_AREAS = [
  "Agriculture",
  "Arts",
  "Business and Commerce",
  "Community Development",
  "Consumer Protection",
  "Disaster Prevention and Relief",
  "Education",
  "Employment, Labor, and Training",
  "Energy",
  "Environment",
  "Food and Nutrition",
  "Health",
  "Housing",
  "Humanities",
  "Income Security and Social Services",
  "Information and Statistics",
  "Law, Justice, and Legal Services",
  "Natural Resources",
  "Regional Development",
  "Science and Technology",
  "Transportation",
  "Other",
];

export const FOCUS_TO_CATEGORY: Record<string, string> = {
  "Agriculture": "AG",
  "Arts": "AR",
  "Business and Commerce": "BC",
  "Community Development": "CD",
  "Consumer Protection": "CP",
  "Disaster Prevention and Relief": "DPR",
  "Education": "ED",
  "Employment, Labor, and Training": "ELT",
  "Energy": "EN",
  "Environment": "ENV",
  "Food and Nutrition": "FN",
  "Health": "HL",
  "Housing": "HO",
  "Humanities": "HU",
  "Income Security and Social Services": "ISS",
  "Information and Statistics": "IS",
  "Law, Justice, and Legal Services": "LJL",
  "Natural Resources": "NR",
  "Regional Development": "RD",
  "Science and Technology": "ST",
  "Transportation": "T",
};
