import Link from 'next/link';

export function LegalDocument() {
  return (
    <main className="min-h-screen">
      <header className="border-b border-border">
        <div className="max-w-3xl mx-auto px-6 py-5 flex items-center justify-between">
          <h1 className="text-lg font-semibold text-foreground">Terms of Service &amp; Privacy Policy</h1>
          <Link
            href="/login"
            className="text-sm text-muted hover:text-foreground transition-colors"
          >
            Back to sign in
          </Link>
        </div>
      </header>

      <article className="max-w-3xl mx-auto px-6 py-10 prose-legal">
        <p className="text-sm text-muted mb-8">Last updated: April 21, 2026</p>

        <Section title="About this service">
          <p>
            This web application (the &quot;Service&quot;) is a complimentary, optional tool
            provided by Daybooks Web Solutions LLC, doing business as connectNPO
            (&quot;connectNPO&quot;, &quot;we&quot;, &quot;us&quot;). The Service is offered
            to clients of GivingArc (another d/b/a of Daybooks Web Solutions LLC) who have
            an active bookkeeping engagement with GivingArc.
          </p>
          <p>
            Your monthly financial statements continue to be delivered to you as Excel
            spreadsheets as part of your bookkeeping engagement, regardless of whether you
            use this Service. Your official financial records are those Excel statements,
            not anything displayed or generated by this Service.
          </p>
          <p>
            Use of this Service is entirely voluntary. You may choose not to use it, or
            stop using it at any time, with no effect on your bookkeeping engagement.
          </p>
        </Section>

        <h2 id="terms" className="text-xl font-semibold text-foreground mt-12 mb-4">
          Terms of Service
        </h2>

        <Section title="1. Eligibility">
          <p>
            To create an account, you must be an authorized representative of an
            organization that has an active bookkeeping engagement with GivingArc. By
            creating an account, you confirm you have that authority.
          </p>
        </Section>

        <Section title="2. Acceptable use">
          <p>You agree to:</p>
          <ul>
            <li>Upload only financial data for organizations you are authorized to represent.</li>
            <li>Not attempt to reverse-engineer, scrape, or disrupt the Service.</li>
            <li>Not upload content that violates any law or third-party right.</li>
            <li>Keep your login credentials confidential and notify us of any suspected unauthorized access.</li>
          </ul>
        </Section>

        <Section title="3. AI features are optional">
          <p>
            The Service includes optional AI-generated features (such as Executive
            Summary, Board Q&amp;A Prep, and Chart Explanations) powered by
            Anthropic&apos;s Claude API. These features run only when you click the
            corresponding button. You may use the Service without invoking them, in which
            case none of your uploaded data is sent to Anthropic.
          </p>
          <p>
            Details about how data flows to Anthropic when you use an AI feature are in
            the Privacy Policy below.
          </p>
        </Section>

        <Section title="4. Accuracy and reliance">
          <p>
            AI-generated content is provided as a drafting aid only. We do not certify the
            accuracy or completeness of AI output. You should independently
            verify any AI-generated summary, recommendation, or explanation before
            relying on it for board presentations, regulatory filings, grant
            applications, tax filings, or financial decisions.
          </p>
          <p>
            Your official financial records are the Excel financial statements delivered
            to you as part of your bookkeeping engagement, not anything produced by this
            Service.
          </p>
        </Section>

        <Section title="5. As-is, no warranty">
          <p>
            The Service is provided on an &quot;as-is&quot; and &quot;as-available&quot;
            basis, without warranties of any kind, whether express or implied, including
            warranties of merchantability, fitness for a particular purpose, or
            non-infringement. We do not warrant that the Service will be uninterrupted,
            error-free, secure, or produce any particular result.
          </p>
        </Section>

        <Section title="6. Limitation of liability">
          <p>
            To the fullest extent permitted by law, our aggregate liability arising out
            of or relating to your use of the Service is limited to one hundred U.S.
            dollars (USD $100). We are not liable for indirect, incidental, consequential,
            special, or punitive damages, including lost profits, lost revenue, or data
            loss.
          </p>
          <p>
            This limitation applies only to this Service. It does not limit or modify
            GivingArc&apos;s separate obligations to you under your bookkeeping
            engagement letter with GivingArc, which continue in full force.
          </p>
        </Section>

        <Section title="7. Service changes and termination">
          <p>
            We may modify, suspend, or discontinue the Service, or any feature, at any
            time, with or without notice. We may terminate your access to the Service for
            violation of these Terms or at our discretion. Termination of your Service
            account does not terminate your bookkeeping engagement, and vice versa.
          </p>
        </Section>

        <Section title="8. Governing law">
          <p>
            These Terms are governed by the laws of the State of California, without
            regard to conflict of laws principles. Any dispute arising from these Terms
            or the Service will be resolved in the state or federal courts located in
            California.
          </p>
        </Section>

        <Section title="9. Changes to these terms">
          <p>
            We may update these Terms from time to time. When we do, we will update the
            &quot;Last updated&quot; date at the top of this page. Your continued use of
            the Service after an update means you accept the updated Terms.
          </p>
        </Section>

        <h2 id="privacy" className="text-xl font-semibold text-foreground mt-12 mb-4">
          Privacy Policy
        </h2>

        <Section title="10. Data we collect">
          <ul>
            <li>
              <strong>Account data:</strong> your email address, a hashed password, and
              the organization name you provide at signup, managed through our
              authentication provider, Supabase.
            </li>
            <li>
              <strong>Financial data you upload:</strong> Excel or CSV files containing
              account balances, revenue, expenses, and project breakdowns.
            </li>
            <li>
              <strong>Technical data:</strong> standard server logs (IP address,
              timestamps, request metadata) maintained by our hosting provider, Vercel.
            </li>
          </ul>
        </Section>

        <Section title="11. How we handle uploaded files">
          <p>When you upload a spreadsheet:</p>
          <ul>
            <li>The file is parsed in server memory and discarded immediately after parsing.</li>
            <li>We do not write the file to disk on our servers.</li>
            <li>
              The parsed numeric data is sent to your browser and stored only in your
              browser&apos;s <code>sessionStorage</code>, which is cleared automatically
              when you close the browser tab.
            </li>
          </ul>
        </Section>

        <Section title="12. AI processing (Anthropic Claude API)">
          <p>
            If you click an AI feature button, the parsed data from your upload
            (organization name, account categories, amounts) is sent to Anthropic&apos;s
            Claude API to generate the requested output.
          </p>
          <p>Per Anthropic&apos;s Commercial Terms:</p>
          <ul>
            <li>
              <strong>Anthropic does not use API data to train their models.</strong>
            </li>
            <li>
              Anthropic retains API requests for up to 30 days for abuse detection only.
              This is automated safety scanning; no human reviews the content unless a
              safety flag is triggered.
            </li>
            <li>
              Anthropic&apos;s consumer product (claude.ai) is a separate service with
              different terms. This Service uses only the API.
            </li>
          </ul>
          <p>
            You can review Anthropic&apos;s terms at{' '}
            <a
              href="https://www.anthropic.com/legal/commercial-terms"
              className="underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              anthropic.com/legal/commercial-terms
            </a>
            .
          </p>
        </Section>

        <Section title="13. Data sharing">
          <p>We do not sell or rent your data. We share data only with:</p>
          <ul>
            <li>
              <strong>Anthropic</strong>, when you invoke an AI feature (see the section
              above).
            </li>
            <li>
              <strong>Supabase</strong>, our authentication provider, which stores your
              email and hashed password.
            </li>
            <li>
              <strong>Vercel</strong>, our hosting provider, which stores standard server
              logs.
            </li>
            <li>
              Law enforcement or other parties, when required by valid legal process.
            </li>
          </ul>
        </Section>

        <Section title="14. Your choices">
          <ul>
            <li>
              You may use the Service without invoking AI features. When you do, no data
              is sent to Anthropic.
            </li>
            <li>
              You may delete your account by emailing{' '}
              <a href="mailto:info@connectnpo.com" className="underline">
                info@connectnpo.com
              </a>
              . We will delete your authentication record within 30 days.
            </li>
            <li>
              You may stop using the Service at any time. Once you close the browser tab,
              nothing from your session is retained on our servers.
            </li>
          </ul>
        </Section>

        <Section title="15. Security">
          <p>
            We use HTTPS in transit and rely on Supabase-managed authentication for login
            credentials. No system is perfectly secure. If we become aware of a security
            breach affecting your account data, we will notify you promptly.
          </p>
        </Section>

        <Section title="16. Children">
          <p>
            The Service is not directed to children under 13. We do not knowingly collect
            data from children. If you believe a child has created an account, please
            contact us so we can remove it.
          </p>
        </Section>

        <Section title="17. California and EU residents">
          <p>
            If you are a California resident, you have rights under the California
            Consumer Privacy Act (CCPA), including the right to know, delete, and opt out
            of sale of personal information. (We do not sell personal information.)
          </p>
          <p>
            If you are an EU/EEA or UK resident, you have rights under the GDPR or UK
            GDPR, including the rights of access, rectification, erasure, and data
            portability.
          </p>
          <p>
            To exercise any of these rights, email{' '}
            <a href="mailto:info@connectnpo.com" className="underline">
              info@connectnpo.com
            </a>
            .
          </p>
        </Section>

        <Section title="18. Contact">
          <p>
            Daybooks Web Solutions LLC dba connectNPO
            <br />
            Email:{' '}
            <a href="mailto:info@connectnpo.com" className="underline">
              info@connectnpo.com
            </a>
          </p>
        </Section>

        <p className="text-sm text-muted mt-12 pt-6 border-t border-border">
          By creating an account and using this Service, you confirm you have read and
          agree to these Terms of Service and Privacy Policy.
        </p>
      </article>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h3 className="text-base font-semibold text-foreground mb-3">{title}</h3>
      <div className="space-y-3 text-sm text-foreground leading-relaxed">{children}</div>
    </section>
  );
}
